# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce74b93155ea7c6a6a917bf4e854290f1699efc3ff55a0ae118042e2ebbfa9fac35fb4ce7331ffb68fd78cd3b9219f8551fdc4cf341ae8fdba6b1e5b587de361

test:
  secret_key_base: 0ac14f5e85fa101c702f397df94ea4ce04c07fb55be0ae6cb5ce738c82043e0ec37836b791a07ae43aab51c810c26088e9cb6826c807b130c352cfef61130f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
